USE MiniInsta;
GO
insert into dbo.Post (ID, UserID, LocationName) values (1, 51, 'Lykóvrysi');
insert into dbo.Post (ID, UserID, LocationName) values (2, 196, 'Bueng Kum');
insert into dbo.Post (ID, UserID, LocationName) values (3, 63, 'Aparecida do Taboado');
insert into dbo.Post (ID, UserID, LocationName) values (4, 135, 'Lagarto');
insert into dbo.Post (ID, UserID, LocationName) values (5, 200, 'Saurama');
insert into dbo.Post (ID, UserID, LocationName) values (6, 103, 'Kaédi');
insert into dbo.Post (ID, UserID, LocationName) values (7, 181, 'Daugavgrīva');
insert into dbo.Post (ID, UserID, LocationName) values (8, 155, 'Río Ceballos');
insert into dbo.Post (ID, UserID, LocationName) values (9, 5, 'Shashi');
insert into dbo.Post (ID, UserID, LocationName) values (10, 42, 'Hässleholm');
insert into dbo.Post (ID, UserID, LocationName) values (11, 148, 'Bairro dos Marinheiros');
insert into dbo.Post (ID, UserID, LocationName) values (12, 19, 'Torrevieja');
insert into dbo.Post (ID, UserID, LocationName) values (13, 183, 'Pulau Pinang');
insert into dbo.Post (ID, UserID, LocationName) values (14, 180, 'Latung');
insert into dbo.Post (ID, UserID, LocationName) values (15, 104, 'Noisy-le-Grand');
insert into dbo.Post (ID, UserID, LocationName) values (16, 150, 'Fushë-Bulqizë');
insert into dbo.Post (ID, UserID, LocationName) values (17, 145, 'Maebashi-shi');
insert into dbo.Post (ID, UserID, LocationName) values (18, 170, 'Mae Wang');
insert into dbo.Post (ID, UserID, LocationName) values (19, 68, 'Sukasenang');
insert into dbo.Post (ID, UserID, LocationName) values (20, 93, 'Loma Bonita');
insert into dbo.Post (ID, UserID, LocationName) values (21, 5, 'Brzozów');
insert into dbo.Post (ID, UserID, LocationName) values (22, 185, 'Isfara');
insert into dbo.Post (ID, UserID, LocationName) values (23, 86, 'San Patricio');
insert into dbo.Post (ID, UserID, LocationName) values (24, 187, 'Kraslice');
insert into dbo.Post (ID, UserID, LocationName) values (25, 189, 'White River');
insert into dbo.Post (ID, UserID, LocationName) values (26, 186, 'Kostomuksha');
insert into dbo.Post (ID, UserID, LocationName) values (27, 120, 'Tamiso');
insert into dbo.Post (ID, UserID, LocationName) values (28, 88, 'Sembung');
insert into dbo.Post (ID, UserID, LocationName) values (29, 127, 'Driyorejo');
insert into dbo.Post (ID, UserID, LocationName) values (30, 186, 'Zengji');
insert into dbo.Post (ID, UserID, LocationName) values (31, 102, 'Chuzhou');
insert into dbo.Post (ID, UserID, LocationName) values (32, 59, 'Artsvanist');
insert into dbo.Post (ID, UserID, LocationName) values (33, 30, 'Halmstad');
insert into dbo.Post (ID, UserID, LocationName) values (34, 9, 'Phra Phutthabat');
insert into dbo.Post (ID, UserID, LocationName) values (35, 13, 'Preobrazheniye');
insert into dbo.Post (ID, UserID, LocationName) values (36, 77, 'Penedo');
insert into dbo.Post (ID, UserID, LocationName) values (37, 187, 'Pryluky');
insert into dbo.Post (ID, UserID, LocationName) values (38, 53, 'Bungu');
insert into dbo.Post (ID, UserID, LocationName) values (39, 90, 'Liuji');
insert into dbo.Post (ID, UserID, LocationName) values (40, 74, 'Nyapar');
insert into dbo.Post (ID, UserID, LocationName) values (41, 135, 'Binhe');
insert into dbo.Post (ID, UserID, LocationName) values (42, 199, 'Thị Trấn Na Sầm');
insert into dbo.Post (ID, UserID, LocationName) values (43, 127, 'Gardutanjak');
insert into dbo.Post (ID, UserID, LocationName) values (44, 75, 'Jaguarari');
insert into dbo.Post (ID, UserID, LocationName) values (45, 110, 'Lavaur');
insert into dbo.Post (ID, UserID, LocationName) values (46, 197, 'Ząbkowice Śląskie');
insert into dbo.Post (ID, UserID, LocationName) values (47, 36, 'Zhujiapu');
insert into dbo.Post (ID, UserID, LocationName) values (48, 27, 'Rungis');
insert into dbo.Post (ID, UserID, LocationName) values (49, 4, 'Primorskiy');
insert into dbo.Post (ID, UserID, LocationName) values (50, 48, 'Kedungtulup');
insert into dbo.Post (ID, UserID, LocationName) values (51, 154, 'Västerhaninge');
insert into dbo.Post (ID, UserID, LocationName) values (52, 62, 'Katuli');
insert into dbo.Post (ID, UserID, LocationName) values (53, 27, 'Tangzha');
insert into dbo.Post (ID, UserID, LocationName) values (54, 56, 'Honglin');
insert into dbo.Post (ID, UserID, LocationName) values (55, 131, 'Zambujeira do Mar');
insert into dbo.Post (ID, UserID, LocationName) values (56, 117, 'Pingdingshan');
insert into dbo.Post (ID, UserID, LocationName) values (57, 58, 'Jām Sāhib');
insert into dbo.Post (ID, UserID, LocationName) values (58, 171, 'Wilkowice');
insert into dbo.Post (ID, UserID, LocationName) values (59, 194, 'Akhmīm');
insert into dbo.Post (ID, UserID, LocationName) values (60, 189, 'Shangyi');
insert into dbo.Post (ID, UserID, LocationName) values (61, 154, 'Yinxi');
insert into dbo.Post (ID, UserID, LocationName) values (62, 134, 'Winong');
insert into dbo.Post (ID, UserID, LocationName) values (63, 108, 'Ambat');
insert into dbo.Post (ID, UserID, LocationName) values (64, 93, 'Sizao');
insert into dbo.Post (ID, UserID, LocationName) values (65, 19, 'Salsipuedes');
insert into dbo.Post (ID, UserID, LocationName) values (66, 155, 'Pompano Beach');
insert into dbo.Post (ID, UserID, LocationName) values (67, 71, 'San Gil');
insert into dbo.Post (ID, UserID, LocationName) values (68, 113, 'Aime');
insert into dbo.Post (ID, UserID, LocationName) values (69, 97, 'Shiyuetian');
insert into dbo.Post (ID, UserID, LocationName) values (70, 16, 'Kalanchak');
insert into dbo.Post (ID, UserID, LocationName) values (71, 83, 'Comagascas');
insert into dbo.Post (ID, UserID, LocationName) values (72, 78, 'Norrköping');
insert into dbo.Post (ID, UserID, LocationName) values (73, 155, 'Shangtian');
insert into dbo.Post (ID, UserID, LocationName) values (74, 120, 'Semënovskoye');
insert into dbo.Post (ID, UserID, LocationName) values (75, 47, 'Sumberagung');
insert into dbo.Post (ID, UserID, LocationName) values (76, 83, 'Thành Phố Lạng Sơn');
insert into dbo.Post (ID, UserID, LocationName) values (77, 134, 'Puerto Cisnes');
insert into dbo.Post (ID, UserID, LocationName) values (78, 78, 'Kezileboyi');
insert into dbo.Post (ID, UserID, LocationName) values (79, 5, 'Chengxiang');
insert into dbo.Post (ID, UserID, LocationName) values (80, 54, 'Guazhou');
insert into dbo.Post (ID, UserID, LocationName) values (81, 122, 'Teseney');
insert into dbo.Post (ID, UserID, LocationName) values (82, 130, 'Avignon');
insert into dbo.Post (ID, UserID, LocationName) values (83, 45, 'Rawasan');
insert into dbo.Post (ID, UserID, LocationName) values (84, 99, 'Maayong Tubig');
insert into dbo.Post (ID, UserID, LocationName) values (85, 152, 'Ignacio Zaragoza');
insert into dbo.Post (ID, UserID, LocationName) values (86, 21, 'Xiong’erzhai');
insert into dbo.Post (ID, UserID, LocationName) values (87, 196, 'Želiv');
insert into dbo.Post (ID, UserID, LocationName) values (88, 190, 'Nenotes');
insert into dbo.Post (ID, UserID, LocationName) values (89, 26, 'Moca');
insert into dbo.Post (ID, UserID, LocationName) values (90, 148, 'Sidaurip');
insert into dbo.Post (ID, UserID, LocationName) values (91, 6, 'Malusac');
insert into dbo.Post (ID, UserID, LocationName) values (92, 130, 'Teknāf');
insert into dbo.Post (ID, UserID, LocationName) values (93, 165, 'Boronów');
insert into dbo.Post (ID, UserID, LocationName) values (94, 5, 'Shanglaxiu');
insert into dbo.Post (ID, UserID, LocationName) values (95, 112, 'Venlo');
insert into dbo.Post (ID, UserID, LocationName) values (96, 157, 'Bogor');
insert into dbo.Post (ID, UserID, LocationName) values (97, 152, 'Xiyuan');
insert into dbo.Post (ID, UserID, LocationName) values (98, 66, 'Ronov nad Doubravou');
insert into dbo.Post (ID, UserID, LocationName) values (99, 24, 'Tingqian');
insert into dbo.Post (ID, UserID, LocationName) values (100, 98, 'Murillo');
insert into dbo.Post (ID, UserID, LocationName) values (101, 171, 'Santa Ana Huista');
insert into dbo.Post (ID, UserID, LocationName) values (102, 55, 'Mỏ Cày');
insert into dbo.Post (ID, UserID, LocationName) values (103, 168, 'Michałowice');
insert into dbo.Post (ID, UserID, LocationName) values (104, 122, 'Enshi');
insert into dbo.Post (ID, UserID, LocationName) values (105, 53, 'Svobody');
insert into dbo.Post (ID, UserID, LocationName) values (106, 166, 'Aurora');
insert into dbo.Post (ID, UserID, LocationName) values (107, 183, 'Ratchathewi');
insert into dbo.Post (ID, UserID, LocationName) values (108, 99, 'Shanjeev Home');
insert into dbo.Post (ID, UserID, LocationName) values (109, 197, 'Sharkawshchyna');
insert into dbo.Post (ID, UserID, LocationName) values (110, 108, 'Tungdor');
insert into dbo.Post (ID, UserID, LocationName) values (111, 123, 'Vereshchagino');
insert into dbo.Post (ID, UserID, LocationName) values (112, 36, 'Shchëkino');
insert into dbo.Post (ID, UserID, LocationName) values (113, 194, 'Saitama');
insert into dbo.Post (ID, UserID, LocationName) values (114, 132, 'Khārān');
insert into dbo.Post (ID, UserID, LocationName) values (115, 167, 'Xia Zanggor');
insert into dbo.Post (ID, UserID, LocationName) values (116, 5, 'Sukorejo');
insert into dbo.Post (ID, UserID, LocationName) values (117, 135, 'Sattahip');
insert into dbo.Post (ID, UserID, LocationName) values (118, 170, 'Cabrero');
insert into dbo.Post (ID, UserID, LocationName) values (119, 84, 'Musalerr');
insert into dbo.Post (ID, UserID, LocationName) values (120, 95, 'Dunlewy');
insert into dbo.Post (ID, UserID, LocationName) values (121, 17, 'Jasaan');
insert into dbo.Post (ID, UserID, LocationName) values (122, 87, 'Nanshi');
insert into dbo.Post (ID, UserID, LocationName) values (123, 198, 'Fernando Gutierrez Barrios');
insert into dbo.Post (ID, UserID, LocationName) values (124, 8, 'Yangzhou');
insert into dbo.Post (ID, UserID, LocationName) values (125, 79, 'Saint-Cloud');
insert into dbo.Post (ID, UserID, LocationName) values (126, 134, 'Lázně Kynžvart');
insert into dbo.Post (ID, UserID, LocationName) values (127, 169, 'Kadupayung');
insert into dbo.Post (ID, UserID, LocationName) values (128, 172, 'Verdizela');
insert into dbo.Post (ID, UserID, LocationName) values (129, 100, 'Jimaguayú');
insert into dbo.Post (ID, UserID, LocationName) values (130, 160, 'Sobreira');
insert into dbo.Post (ID, UserID, LocationName) values (131, 138, 'Newtown');
insert into dbo.Post (ID, UserID, LocationName) values (132, 90, 'Tubajon');
insert into dbo.Post (ID, UserID, LocationName) values (133, 114, 'Žebrák');
insert into dbo.Post (ID, UserID, LocationName) values (134, 153, 'Kisovec');
insert into dbo.Post (ID, UserID, LocationName) values (135, 6, 'Yangkou');
insert into dbo.Post (ID, UserID, LocationName) values (136, 32, 'Da’an');
insert into dbo.Post (ID, UserID, LocationName) values (137, 146, 'Kinamayan');
insert into dbo.Post (ID, UserID, LocationName) values (138, 167, 'Jacksonville');
insert into dbo.Post (ID, UserID, LocationName) values (139, 171, 'Bianxiong');
insert into dbo.Post (ID, UserID, LocationName) values (140, 154, 'Severskaya');
insert into dbo.Post (ID, UserID, LocationName) values (141, 63, 'Mahuta');
insert into dbo.Post (ID, UserID, LocationName) values (142, 85, 'Bugko');
insert into dbo.Post (ID, UserID, LocationName) values (143, 97, 'Ban Talat Bueng');
insert into dbo.Post (ID, UserID, LocationName) values (144, 171, 'Hubynykha');
insert into dbo.Post (ID, UserID, LocationName) values (145, 57, 'Yeni Suraxanı');
insert into dbo.Post (ID, UserID, LocationName) values (146, 77, 'Sapphaya');
insert into dbo.Post (ID, UserID, LocationName) values (147, 125, 'Jahrom');
insert into dbo.Post (ID, UserID, LocationName) values (148, 155, 'Bagakay');
insert into dbo.Post (ID, UserID, LocationName) values (149, 19, 'Borzechów');
insert into dbo.Post (ID, UserID, LocationName) values (150, 120, 'Siocon');
insert into dbo.Post (ID, UserID, LocationName) values (151, 113, 'Dibulla');
insert into dbo.Post (ID, UserID, LocationName) values (152, 21, 'Horní Počaply');
insert into dbo.Post (ID, UserID, LocationName) values (153, 171, 'Marsa Alam');
insert into dbo.Post (ID, UserID, LocationName) values (154, 157, 'København');
insert into dbo.Post (ID, UserID, LocationName) values (155, 3, 'Chavusy');
insert into dbo.Post (ID, UserID, LocationName) values (156, 25, 'Dongyuan');
insert into dbo.Post (ID, UserID, LocationName) values (157, 139, 'Changbu');
insert into dbo.Post (ID, UserID, LocationName) values (158, 170, 'Usman’');
insert into dbo.Post (ID, UserID, LocationName) values (159, 16, 'Stockholm');
insert into dbo.Post (ID, UserID, LocationName) values (160, 92, 'Sadahayu');
insert into dbo.Post (ID, UserID, LocationName) values (161, 121, 'Solna');
insert into dbo.Post (ID, UserID, LocationName) values (162, 77, 'Salamnunggal');
insert into dbo.Post (ID, UserID, LocationName) values (163, 19, 'Białogard');
insert into dbo.Post (ID, UserID, LocationName) values (164, 142, 'Ballybofey');
insert into dbo.Post (ID, UserID, LocationName) values (165, 1, 'Nan’ao');
insert into dbo.Post (ID, UserID, LocationName) values (166, 134, 'Sūrān');
insert into dbo.Post (ID, UserID, LocationName) values (167, 182, 'Rublëvo');
insert into dbo.Post (ID, UserID, LocationName) values (168, 53, 'Maturín');
insert into dbo.Post (ID, UserID, LocationName) values (169, 121, 'Gonābād');
insert into dbo.Post (ID, UserID, LocationName) values (170, 93, 'Andong');
insert into dbo.Post (ID, UserID, LocationName) values (171, 96, 'Mairana');
insert into dbo.Post (ID, UserID, LocationName) values (172, 199, 'Xiangzhu');
insert into dbo.Post (ID, UserID, LocationName) values (173, 140, 'Stakhanov');
insert into dbo.Post (ID, UserID, LocationName) values (174, 150, 'L''Île-Perrot');
insert into dbo.Post (ID, UserID, LocationName) values (175, 75, 'Richmond');
insert into dbo.Post (ID, UserID, LocationName) values (176, 153, 'Havana');
insert into dbo.Post (ID, UserID, LocationName) values (177, 43, 'Iwanai');
insert into dbo.Post (ID, UserID, LocationName) values (178, 22, 'General Roca');
insert into dbo.Post (ID, UserID, LocationName) values (179, 195, 'Bata Tengah');
insert into dbo.Post (ID, UserID, LocationName) values (180, 177, 'Tangping');
insert into dbo.Post (ID, UserID, LocationName) values (181, 88, 'Ochota');
insert into dbo.Post (ID, UserID, LocationName) values (182, 118, 'Itum-Kali');
insert into dbo.Post (ID, UserID, LocationName) values (183, 87, 'Getulio');
insert into dbo.Post (ID, UserID, LocationName) values (184, 102, 'Pilcuyo');
insert into dbo.Post (ID, UserID, LocationName) values (185, 19, 'Koło');
insert into dbo.Post (ID, UserID, LocationName) values (186, 12, 'Galátsi');
insert into dbo.Post (ID, UserID, LocationName) values (187, 168, 'Janowice');
insert into dbo.Post (ID, UserID, LocationName) values (188, 190, 'Kohila');
insert into dbo.Post (ID, UserID, LocationName) values (189, 195, 'Bungbulang');
insert into dbo.Post (ID, UserID, LocationName) values (190, 194, 'Dongtundu');
insert into dbo.Post (ID, UserID, LocationName) values (191, 117, 'Kyŏngsŏng');
insert into dbo.Post (ID, UserID, LocationName) values (192, 174, 'Aguiar da Beira');
insert into dbo.Post (ID, UserID, LocationName) values (193, 104, 'Kujung');
insert into dbo.Post (ID, UserID, LocationName) values (194, 186, 'Tentúgal');
insert into dbo.Post (ID, UserID, LocationName) values (195, 97, 'Changshu City');
insert into dbo.Post (ID, UserID, LocationName) values (196, 107, 'Vidago');
insert into dbo.Post (ID, UserID, LocationName) values (197, 7, 'Torres');
insert into dbo.Post (ID, UserID, LocationName) values (198, 90, 'Qinghua');
insert into dbo.Post (ID, UserID, LocationName) values (199, 1, 'Krajan');
insert into dbo.Post (ID, UserID, LocationName) values (200, 160, 'Mogoditshane');
insert into dbo.Post (ID, UserID, LocationName) values (201, 197, 'Velké Meziříčí');
insert into dbo.Post (ID, UserID, LocationName) values (202, 98, 'Trzcianka');
insert into dbo.Post (ID, UserID, LocationName) values (203, 12, 'Ljungbyholm');
insert into dbo.Post (ID, UserID, LocationName) values (204, 157, 'Caçador');
insert into dbo.Post (ID, UserID, LocationName) values (205, 170, 'Maria Aurora');
insert into dbo.Post (ID, UserID, LocationName) values (206, 188, 'Niushou');
insert into dbo.Post (ID, UserID, LocationName) values (207, 200, 'Marāveh Tappeh');
insert into dbo.Post (ID, UserID, LocationName) values (208, 156, 'Walferdange');
insert into dbo.Post (ID, UserID, LocationName) values (209, 157, 'Fiais da Beira');
insert into dbo.Post (ID, UserID, LocationName) values (210, 13, 'Dve Mogili');
insert into dbo.Post (ID, UserID, LocationName) values (211, 27, 'Thành Phố Lạng Sơn');
insert into dbo.Post (ID, UserID, LocationName) values (212, 177, 'Beidong');
insert into dbo.Post (ID, UserID, LocationName) values (213, 7, 'Tala');
insert into dbo.Post (ID, UserID, LocationName) values (214, 32, 'Francisco Villa');
insert into dbo.Post (ID, UserID, LocationName) values (215, 78, 'Puolanka');
insert into dbo.Post (ID, UserID, LocationName) values (216, 188, 'Sibulan');
insert into dbo.Post (ID, UserID, LocationName) values (217, 148, 'Hali');
insert into dbo.Post (ID, UserID, LocationName) values (218, 127, 'Brinkmann');
insert into dbo.Post (ID, UserID, LocationName) values (219, 32, 'La Soledad');
insert into dbo.Post (ID, UserID, LocationName) values (220, 184, 'Shanjiang');
insert into dbo.Post (ID, UserID, LocationName) values (221, 157, 'Tasböget');
insert into dbo.Post (ID, UserID, LocationName) values (222, 159, 'São Roque');
insert into dbo.Post (ID, UserID, LocationName) values (223, 131, 'Krajan');
insert into dbo.Post (ID, UserID, LocationName) values (224, 102, 'Doropeti');
insert into dbo.Post (ID, UserID, LocationName) values (225, 62, 'Guanqian');
insert into dbo.Post (ID, UserID, LocationName) values (226, 7, 'Soroti');
insert into dbo.Post (ID, UserID, LocationName) values (227, 178, 'Janagdong');
insert into dbo.Post (ID, UserID, LocationName) values (228, 150, 'Zaslawye');
insert into dbo.Post (ID, UserID, LocationName) values (229, 177, 'Jiexiu');
insert into dbo.Post (ID, UserID, LocationName) values (230, 46, 'Şalākhid');
insert into dbo.Post (ID, UserID, LocationName) values (231, 66, 'Tucdao');
insert into dbo.Post (ID, UserID, LocationName) values (232, 128, 'Juncheng');
insert into dbo.Post (ID, UserID, LocationName) values (233, 199, 'Las Tejerías');
insert into dbo.Post (ID, UserID, LocationName) values (234, 161, 'Chaoyang');
insert into dbo.Post (ID, UserID, LocationName) values (235, 90, 'Le Mans');
insert into dbo.Post (ID, UserID, LocationName) values (236, 61, 'Vreshtas');
insert into dbo.Post (ID, UserID, LocationName) values (237, 140, 'Guanmiao');
insert into dbo.Post (ID, UserID, LocationName) values (238, 103, 'Gibato');
insert into dbo.Post (ID, UserID, LocationName) values (239, 145, 'Malusac');
insert into dbo.Post (ID, UserID, LocationName) values (240, 108, 'Makarov');
insert into dbo.Post (ID, UserID, LocationName) values (241, 68, 'Pristen’');
insert into dbo.Post (ID, UserID, LocationName) values (242, 183, 'Xiting');
insert into dbo.Post (ID, UserID, LocationName) values (243, 10, 'Kamubheka');
insert into dbo.Post (ID, UserID, LocationName) values (244, 98, 'Emplak');
insert into dbo.Post (ID, UserID, LocationName) values (245, 110, 'São Paulo');
insert into dbo.Post (ID, UserID, LocationName) values (246, 14, 'Chesma');
insert into dbo.Post (ID, UserID, LocationName) values (247, 49, 'Preobrazhenka');
insert into dbo.Post (ID, UserID, LocationName) values (248, 194, 'Wasilków');
insert into dbo.Post (ID, UserID, LocationName) values (249, 47, 'Asykata');
insert into dbo.Post (ID, UserID, LocationName) values (250, 58, 'Chantal');
insert into dbo.Post (ID, UserID, LocationName) values (251, 182, 'Penebel');
insert into dbo.Post (ID, UserID, LocationName) values (252, 53, 'Changkeng');
insert into dbo.Post (ID, UserID, LocationName) values (253, 143, 'Ambelón');
insert into dbo.Post (ID, UserID, LocationName) values (254, 129, 'Darband');
insert into dbo.Post (ID, UserID, LocationName) values (255, 64, 'Duyang');
insert into dbo.Post (ID, UserID, LocationName) values (256, 36, 'Luowan');
insert into dbo.Post (ID, UserID, LocationName) values (257, 83, 'Wangsi');
insert into dbo.Post (ID, UserID, LocationName) values (258, 110, 'Peachland');
insert into dbo.Post (ID, UserID, LocationName) values (259, 62, 'Solidaridad');
insert into dbo.Post (ID, UserID, LocationName) values (260, 200, 'Yessentukskaya');
insert into dbo.Post (ID, UserID, LocationName) values (261, 173, 'Nikhom Phattana');
insert into dbo.Post (ID, UserID, LocationName) values (262, 180, 'Longquan');
insert into dbo.Post (ID, UserID, LocationName) values (263, 44, 'Annau');
insert into dbo.Post (ID, UserID, LocationName) values (264, 69, 'Burauen');
insert into dbo.Post (ID, UserID, LocationName) values (265, 52, 'Bitam');
insert into dbo.Post (ID, UserID, LocationName) values (266, 199, 'Pivka');
insert into dbo.Post (ID, UserID, LocationName) values (267, 152, 'San Marcos');
insert into dbo.Post (ID, UserID, LocationName) values (268, 72, 'Serere');
insert into dbo.Post (ID, UserID, LocationName) values (269, 120, 'Amassoma');
insert into dbo.Post (ID, UserID, LocationName) values (270, 140, 'Tegalsari');
insert into dbo.Post (ID, UserID, LocationName) values (271, 63, 'Machinga');
insert into dbo.Post (ID, UserID, LocationName) values (272, 180, 'El Limon');
insert into dbo.Post (ID, UserID, LocationName) values (273, 189, 'Creil');
insert into dbo.Post (ID, UserID, LocationName) values (274, 164, 'Synevyr');
insert into dbo.Post (ID, UserID, LocationName) values (275, 29, 'La Unión');
insert into dbo.Post (ID, UserID, LocationName) values (276, 166, 'Silver Spring');
insert into dbo.Post (ID, UserID, LocationName) values (277, 40, 'Kalmar');
insert into dbo.Post (ID, UserID, LocationName) values (278, 106, 'Ayang-ni');
insert into dbo.Post (ID, UserID, LocationName) values (279, 48, 'Caomiao');
insert into dbo.Post (ID, UserID, LocationName) values (280, 14, 'Petit Raffray');
insert into dbo.Post (ID, UserID, LocationName) values (281, 24, 'Catujal');
insert into dbo.Post (ID, UserID, LocationName) values (282, 16, 'Chengji');
insert into dbo.Post (ID, UserID, LocationName) values (283, 99, 'Xiaolin');
insert into dbo.Post (ID, UserID, LocationName) values (284, 190, 'Bolnisi');
insert into dbo.Post (ID, UserID, LocationName) values (285, 24, 'Khirdalan');
insert into dbo.Post (ID, UserID, LocationName) values (286, 128, 'Camaçari');
insert into dbo.Post (ID, UserID, LocationName) values (287, 181, 'Ozerne');
insert into dbo.Post (ID, UserID, LocationName) values (288, 1, 'Wąpielsk');
insert into dbo.Post (ID, UserID, LocationName) values (289, 152, 'Huabu');
insert into dbo.Post (ID, UserID, LocationName) values (290, 71, 'Samphanthawong');
insert into dbo.Post (ID, UserID, LocationName) values (291, 176, 'Ifanadiana');
insert into dbo.Post (ID, UserID, LocationName) values (292, 79, 'Nueva Requena');
insert into dbo.Post (ID, UserID, LocationName) values (293, 100, '’Unābah');
insert into dbo.Post (ID, UserID, LocationName) values (294, 44, 'Shakīso');
insert into dbo.Post (ID, UserID, LocationName) values (295, 26, 'Ortega');
insert into dbo.Post (ID, UserID, LocationName) values (296, 156, 'Mbale');
insert into dbo.Post (ID, UserID, LocationName) values (297, 4, 'Pereira');
insert into dbo.Post (ID, UserID, LocationName) values (298, 117, 'Barra do Corda');
insert into dbo.Post (ID, UserID, LocationName) values (299, 127, 'Facatativá');
insert into dbo.Post (ID, UserID, LocationName) values (300, 20, 'Oelui');
insert into dbo.Post (ID, UserID, LocationName) values (301, 199, 'Mamurras');
insert into dbo.Post (ID, UserID, LocationName) values (302, 153, 'Rangmanten');
insert into dbo.Post (ID, UserID, LocationName) values (303, 130, 'Darenzhuang');
insert into dbo.Post (ID, UserID, LocationName) values (304, 17, 'Apače');
insert into dbo.Post (ID, UserID, LocationName) values (305, 172, 'Kute');
insert into dbo.Post (ID, UserID, LocationName) values (306, 47, 'Amarillo');
insert into dbo.Post (ID, UserID, LocationName) values (307, 12, 'Ouro Sogui');
insert into dbo.Post (ID, UserID, LocationName) values (308, 84, 'Chumpi');
insert into dbo.Post (ID, UserID, LocationName) values (309, 22, 'Rawa Mazowiecka');
insert into dbo.Post (ID, UserID, LocationName) values (310, 67, 'Mqabba');
insert into dbo.Post (ID, UserID, LocationName) values (311, 76, 'Panan');
insert into dbo.Post (ID, UserID, LocationName) values (312, 149, 'Daxin');
insert into dbo.Post (ID, UserID, LocationName) values (313, 9, 'Hulan');
insert into dbo.Post (ID, UserID, LocationName) values (314, 83, 'Kireyevsk');
insert into dbo.Post (ID, UserID, LocationName) values (315, 168, 'Plavsk');
insert into dbo.Post (ID, UserID, LocationName) values (316, 72, 'Jangheung');
insert into dbo.Post (ID, UserID, LocationName) values (317, 36, 'Xincheng');
insert into dbo.Post (ID, UserID, LocationName) values (318, 43, 'Cerro Blanco');
insert into dbo.Post (ID, UserID, LocationName) values (319, 106, 'Phonphisai');
insert into dbo.Post (ID, UserID, LocationName) values (320, 172, 'Yixin');
insert into dbo.Post (ID, UserID, LocationName) values (321, 99, 'Hanchang');
insert into dbo.Post (ID, UserID, LocationName) values (322, 85, 'Sang-e Chārak');
insert into dbo.Post (ID, UserID, LocationName) values (323, 107, 'Razumnoye');
insert into dbo.Post (ID, UserID, LocationName) values (324, 35, 'Amsterdam-Oost');
insert into dbo.Post (ID, UserID, LocationName) values (325, 44, 'Santa Rosa de Cabal');
insert into dbo.Post (ID, UserID, LocationName) values (326, 198, 'Lobitos');
insert into dbo.Post (ID, UserID, LocationName) values (327, 102, 'Jasień');
insert into dbo.Post (ID, UserID, LocationName) values (328, 133, 'Votuporanga');
insert into dbo.Post (ID, UserID, LocationName) values (329, 101, 'Chifeng');
insert into dbo.Post (ID, UserID, LocationName) values (330, 185, 'Xin’an');
insert into dbo.Post (ID, UserID, LocationName) values (331, 3, 'Nueva Guadalupe');
insert into dbo.Post (ID, UserID, LocationName) values (332, 105, 'Māmūnīyeh');
insert into dbo.Post (ID, UserID, LocationName) values (333, 150, 'Mandapajaya');
insert into dbo.Post (ID, UserID, LocationName) values (334, 48, 'Sūrak');
insert into dbo.Post (ID, UserID, LocationName) values (335, 98, 'Khafizan');
insert into dbo.Post (ID, UserID, LocationName) values (336, 46, 'Gobernador Gálvez');
insert into dbo.Post (ID, UserID, LocationName) values (337, 26, 'São Domingos de Rana');
insert into dbo.Post (ID, UserID, LocationName) values (338, 191, 'Wińsko');
insert into dbo.Post (ID, UserID, LocationName) values (339, 7, 'Megion');
insert into dbo.Post (ID, UserID, LocationName) values (340, 163, 'Sukmoilang');
insert into dbo.Post (ID, UserID, LocationName) values (341, 26, 'Kawalimukti');
insert into dbo.Post (ID, UserID, LocationName) values (342, 152, 'Roma');
insert into dbo.Post (ID, UserID, LocationName) values (343, 131, 'Villa del Carmen');
insert into dbo.Post (ID, UserID, LocationName) values (344, 114, 'Stockholm');
insert into dbo.Post (ID, UserID, LocationName) values (345, 196, 'Yongyang');
insert into dbo.Post (ID, UserID, LocationName) values (346, 90, 'Bălţi');
insert into dbo.Post (ID, UserID, LocationName) values (347, 186, 'Xiadian');
insert into dbo.Post (ID, UserID, LocationName) values (348, 34, 'Detchino');
insert into dbo.Post (ID, UserID, LocationName) values (349, 81, 'Maghār');
insert into dbo.Post (ID, UserID, LocationName) values (350, 7, 'Mellieħa');
insert into dbo.Post (ID, UserID, LocationName) values (351, 54, 'Xiping');
insert into dbo.Post (ID, UserID, LocationName) values (352, 138, 'Pámfylla');
insert into dbo.Post (ID, UserID, LocationName) values (353, 11, 'Gelatik');
insert into dbo.Post (ID, UserID, LocationName) values (354, 162, 'Liucheng');
insert into dbo.Post (ID, UserID, LocationName) values (355, 157, 'Watulabara');
insert into dbo.Post (ID, UserID, LocationName) values (356, 31, 'Georgiyevsk');
insert into dbo.Post (ID, UserID, LocationName) values (357, 190, 'Limeira');
insert into dbo.Post (ID, UserID, LocationName) values (358, 76, 'Groblersdal');
insert into dbo.Post (ID, UserID, LocationName) values (359, 116, 'Mossoró');
insert into dbo.Post (ID, UserID, LocationName) values (360, 45, 'Springfield');
insert into dbo.Post (ID, UserID, LocationName) values (361, 132, 'Kannus');
insert into dbo.Post (ID, UserID, LocationName) values (362, 54, 'Kobylin');
insert into dbo.Post (ID, UserID, LocationName) values (363, 130, 'Mazkeret Batya');
insert into dbo.Post (ID, UserID, LocationName) values (364, 25, 'Bailang');
insert into dbo.Post (ID, UserID, LocationName) values (365, 132, 'Vilémov');
insert into dbo.Post (ID, UserID, LocationName) values (366, 82, 'Doibang');
insert into dbo.Post (ID, UserID, LocationName) values (367, 70, 'Reading');
insert into dbo.Post (ID, UserID, LocationName) values (368, 23, 'Nelahozeves');
insert into dbo.Post (ID, UserID, LocationName) values (369, 23, 'Tangxi');
insert into dbo.Post (ID, UserID, LocationName) values (370, 142, 'Wanbu');
insert into dbo.Post (ID, UserID, LocationName) values (371, 111, 'Rostov-na-Donu');
insert into dbo.Post (ID, UserID, LocationName) values (372, 95, 'Abuja');
insert into dbo.Post (ID, UserID, LocationName) values (373, 42, 'Larap');
insert into dbo.Post (ID, UserID, LocationName) values (374, 78, 'Canturay');
insert into dbo.Post (ID, UserID, LocationName) values (375, 9, 'Wuchagou');
insert into dbo.Post (ID, UserID, LocationName) values (376, 174, 'Osby');
insert into dbo.Post (ID, UserID, LocationName) values (377, 41, 'Mondim de Basto');
insert into dbo.Post (ID, UserID, LocationName) values (378, 62, 'Bandar-e Lengeh');
insert into dbo.Post (ID, UserID, LocationName) values (379, 195, 'Narail');
insert into dbo.Post (ID, UserID, LocationName) values (380, 29, 'Chenjiahe');
insert into dbo.Post (ID, UserID, LocationName) values (381, 120, 'Huangyang');
insert into dbo.Post (ID, UserID, LocationName) values (382, 190, 'Praia de Mira');
insert into dbo.Post (ID, UserID, LocationName) values (383, 103, 'Barvinkove');
insert into dbo.Post (ID, UserID, LocationName) values (384, 151, 'Nempel');
insert into dbo.Post (ID, UserID, LocationName) values (385, 41, 'Caen');
insert into dbo.Post (ID, UserID, LocationName) values (386, 112, 'Brylivka');
insert into dbo.Post (ID, UserID, LocationName) values (387, 109, 'Seongnam-si');
insert into dbo.Post (ID, UserID, LocationName) values (388, 136, 'Siquanpu');
insert into dbo.Post (ID, UserID, LocationName) values (389, 144, 'Dzerzhinsk');
insert into dbo.Post (ID, UserID, LocationName) values (390, 108, 'Akaki');
insert into dbo.Post (ID, UserID, LocationName) values (391, 177, 'Itaporanga');
insert into dbo.Post (ID, UserID, LocationName) values (392, 200, 'Den Haag');
insert into dbo.Post (ID, UserID, LocationName) values (393, 151, 'Butiama');
insert into dbo.Post (ID, UserID, LocationName) values (394, 72, 'Francos');
insert into dbo.Post (ID, UserID, LocationName) values (395, 72, 'Purorejo');
insert into dbo.Post (ID, UserID, LocationName) values (396, 122, 'Energodar');
insert into dbo.Post (ID, UserID, LocationName) values (397, 87, 'Talā');
insert into dbo.Post (ID, UserID, LocationName) values (398, 6, 'Vostok');
insert into dbo.Post (ID, UserID, LocationName) values (399, 75, 'San Juan Bautista');
insert into dbo.Post (ID, UserID, LocationName) values (400, 103, 'Martil');
insert into dbo.Post (ID, UserID, LocationName) values (401, 105, 'Shīnḏanḏ');
insert into dbo.Post (ID, UserID, LocationName) values (402, 176, 'Isoka');
insert into dbo.Post (ID, UserID, LocationName) values (403, 110, 'Plottier');
insert into dbo.Post (ID, UserID, LocationName) values (404, 187, 'Migori');
insert into dbo.Post (ID, UserID, LocationName) values (405, 71, 'Shaheying');
insert into dbo.Post (ID, UserID, LocationName) values (406, 172, 'Helsingborg');
insert into dbo.Post (ID, UserID, LocationName) values (407, 18, 'Batagay-Alyta');
insert into dbo.Post (ID, UserID, LocationName) values (408, 115, 'Jablanovec');
insert into dbo.Post (ID, UserID, LocationName) values (409, 156, 'Danidehe');
insert into dbo.Post (ID, UserID, LocationName) values (410, 126, 'Tlogoagung');
insert into dbo.Post (ID, UserID, LocationName) values (411, 76, 'Laç');
insert into dbo.Post (ID, UserID, LocationName) values (412, 72, 'Det Udom');
insert into dbo.Post (ID, UserID, LocationName) values (413, 65, 'Baqiu');
insert into dbo.Post (ID, UserID, LocationName) values (414, 190, 'Esperanza');
insert into dbo.Post (ID, UserID, LocationName) values (415, 76, 'Yisuhe');
insert into dbo.Post (ID, UserID, LocationName) values (416, 167, 'Ureshino');
insert into dbo.Post (ID, UserID, LocationName) values (417, 119, 'Winnica');
insert into dbo.Post (ID, UserID, LocationName) values (418, 153, 'Fredrikstad');
insert into dbo.Post (ID, UserID, LocationName) values (419, 153, 'Mamanguape');
insert into dbo.Post (ID, UserID, LocationName) values (420, 30, 'Ilhabela');
insert into dbo.Post (ID, UserID, LocationName) values (421, 36, 'Uchiza');
insert into dbo.Post (ID, UserID, LocationName) values (422, 179, 'Sampués');
insert into dbo.Post (ID, UserID, LocationName) values (423, 159, 'Wang Sai Phun');
insert into dbo.Post (ID, UserID, LocationName) values (424, 150, 'Fengjiang');
insert into dbo.Post (ID, UserID, LocationName) values (425, 86, 'Oslo');
insert into dbo.Post (ID, UserID, LocationName) values (426, 27, 'Pegões');
insert into dbo.Post (ID, UserID, LocationName) values (427, 177, 'Bồng Sơn');
insert into dbo.Post (ID, UserID, LocationName) values (428, 151, 'Torino');
insert into dbo.Post (ID, UserID, LocationName) values (429, 135, 'Kayapa');
insert into dbo.Post (ID, UserID, LocationName) values (430, 12, 'Kortesjärvi');
insert into dbo.Post (ID, UserID, LocationName) values (431, 112, 'Pedro II');
insert into dbo.Post (ID, UserID, LocationName) values (432, 50, 'Sucun');
insert into dbo.Post (ID, UserID, LocationName) values (433, 27, 'Anh Son');
insert into dbo.Post (ID, UserID, LocationName) values (434, 63, 'Rogóźno');
insert into dbo.Post (ID, UserID, LocationName) values (435, 131, 'Nyanza');
insert into dbo.Post (ID, UserID, LocationName) values (436, 104, 'Gangdong');
insert into dbo.Post (ID, UserID, LocationName) values (437, 129, 'Gulu');
insert into dbo.Post (ID, UserID, LocationName) values (438, 174, 'Lýkeio');
insert into dbo.Post (ID, UserID, LocationName) values (439, 18, 'Lantian');
insert into dbo.Post (ID, UserID, LocationName) values (440, 171, 'Além Paraíba');
insert into dbo.Post (ID, UserID, LocationName) values (441, 76, 'Kudinovo');
insert into dbo.Post (ID, UserID, LocationName) values (442, 188, 'Duszniki-Zdrój');
insert into dbo.Post (ID, UserID, LocationName) values (443, 137, 'Jaciara');
insert into dbo.Post (ID, UserID, LocationName) values (444, 68, 'Linmansangan');
insert into dbo.Post (ID, UserID, LocationName) values (445, 129, 'Drammen');
insert into dbo.Post (ID, UserID, LocationName) values (446, 59, 'Maras');
insert into dbo.Post (ID, UserID, LocationName) values (447, 25, 'Powassan');
insert into dbo.Post (ID, UserID, LocationName) values (448, 122, 'Matagbak');
insert into dbo.Post (ID, UserID, LocationName) values (449, 82, 'Yagoua');
insert into dbo.Post (ID, UserID, LocationName) values (450, 18, 'Isu');
insert into dbo.Post (ID, UserID, LocationName) values (451, 2, 'Rokoy');
insert into dbo.Post (ID, UserID, LocationName) values (452, 104, 'Shangma');
insert into dbo.Post (ID, UserID, LocationName) values (453, 166, 'Ncue');
insert into dbo.Post (ID, UserID, LocationName) values (454, 58, 'Huangtukuang');
insert into dbo.Post (ID, UserID, LocationName) values (455, 83, 'Imrīsh');
insert into dbo.Post (ID, UserID, LocationName) values (456, 73, 'Nanping');
insert into dbo.Post (ID, UserID, LocationName) values (457, 151, 'Jiuchi');
insert into dbo.Post (ID, UserID, LocationName) values (458, 13, 'Sasykoli');
insert into dbo.Post (ID, UserID, LocationName) values (459, 67, 'Biruinţa');
insert into dbo.Post (ID, UserID, LocationName) values (460, 149, 'Várzea Grande');
insert into dbo.Post (ID, UserID, LocationName) values (461, 120, 'Ngã Bảy');
insert into dbo.Post (ID, UserID, LocationName) values (462, 172, 'Sisŏphŏn');
insert into dbo.Post (ID, UserID, LocationName) values (463, 155, 'Sel’tso');
insert into dbo.Post (ID, UserID, LocationName) values (464, 141, 'Zhigulevsk');
insert into dbo.Post (ID, UserID, LocationName) values (465, 3, 'Baturaja');
insert into dbo.Post (ID, UserID, LocationName) values (466, 1, 'Marieville');
insert into dbo.Post (ID, UserID, LocationName) values (467, 183, 'Baishigou');
insert into dbo.Post (ID, UserID, LocationName) values (468, 122, 'Trang');
insert into dbo.Post (ID, UserID, LocationName) values (469, 44, 'Kumla');
insert into dbo.Post (ID, UserID, LocationName) values (470, 39, 'Si Khoraphum');
insert into dbo.Post (ID, UserID, LocationName) values (471, 127, 'Oslo');
insert into dbo.Post (ID, UserID, LocationName) values (472, 18, 'Lebowakgomo');
insert into dbo.Post (ID, UserID, LocationName) values (473, 98, 'Zengjia');
insert into dbo.Post (ID, UserID, LocationName) values (474, 45, 'Kegeyli Shahar');
insert into dbo.Post (ID, UserID, LocationName) values (475, 183, 'Chongxian');
insert into dbo.Post (ID, UserID, LocationName) values (476, 149, 'Birmingham');
insert into dbo.Post (ID, UserID, LocationName) values (477, 98, 'Langtad');
insert into dbo.Post (ID, UserID, LocationName) values (478, 86, 'Sumurwaru');
insert into dbo.Post (ID, UserID, LocationName) values (479, 144, 'Sacramento');
insert into dbo.Post (ID, UserID, LocationName) values (480, 27, 'Palguyod');
insert into dbo.Post (ID, UserID, LocationName) values (481, 194, 'Ban Fang');
insert into dbo.Post (ID, UserID, LocationName) values (482, 16, 'Hanover');
insert into dbo.Post (ID, UserID, LocationName) values (483, 35, 'Yūki');
insert into dbo.Post (ID, UserID, LocationName) values (484, 81, 'Krzeszów');
insert into dbo.Post (ID, UserID, LocationName) values (485, 24, 'Ibrā’');
insert into dbo.Post (ID, UserID, LocationName) values (486, 29, 'Armopa');
insert into dbo.Post (ID, UserID, LocationName) values (487, 113, 'Carcavelos');
insert into dbo.Post (ID, UserID, LocationName) values (488, 72, 'Indianapolis');
insert into dbo.Post (ID, UserID, LocationName) values (489, 74, 'Dorotea');
insert into dbo.Post (ID, UserID, LocationName) values (490, 53, 'Shuangkou');
insert into dbo.Post (ID, UserID, LocationName) values (491, 153, 'Shuigou');
insert into dbo.Post (ID, UserID, LocationName) values (492, 179, 'Pamanukan');
insert into dbo.Post (ID, UserID, LocationName) values (493, 180, 'Saurimo');
insert into dbo.Post (ID, UserID, LocationName) values (494, 138, 'Kotel’niki');
insert into dbo.Post (ID, UserID, LocationName) values (495, 128, 'Villa Consuelo');
insert into dbo.Post (ID, UserID, LocationName) values (496, 64, 'Yushu');
insert into dbo.Post (ID, UserID, LocationName) values (497, 15, 'Manhan');
insert into dbo.Post (ID, UserID, LocationName) values (498, 66, 'Abu Dhabi');
insert into dbo.Post (ID, UserID, LocationName) values (499, 49, 'Alepoú');
insert into dbo.Post (ID, UserID, LocationName) values (500, 21, 'Damaishan');
